name: vsaudio
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2   # having default icons which we can use in our app

  path_provider: ^2.0.13   # used to give and find path to files
  intl: ^0.18.0   # internationalization is used for date/number formatting and parsing
  slide_popup_dialog_null_safety: ^1.0.0     # for popups we are using this
  flutter_svprogresshud: ^0.0.3   # it is a progress bar
  permission_handler: ^10.2.0    # for asking run time permissions

  flutter_sound: ^9.2.13   # this is the audio player and also a Stream player
  flutter_bluetooth_seria_changed: ^0.4.0   # this is the BT Classic package for both mobile and pebbl device and communication
  web_socket_channel: ^2.3.0   # for creating web Sockets
  network_info_plus: ^3.0.2   # for getting the wifi network informations
  showcaseview: ^2.0.3   # for overlay texts
  fluttertoast: ^8.2.1   # for toast messages
  share_plus: ^7.0.1    # used in sharing audio files
  file_picker: ^5.2.9   # used to get files from phone storage etc...
  webview_flutter: ^4.0.7    # it creates a in app webview using url
  url_launcher: ^6.1.10    # to launch the url in browser
  binary_codec: ^2.0.3    # used to convert one data types into binary type
  crc32_checksum: ^0.0.2   # used in checksums

  flutter_blue_plus: ^1.4.0   # it is a BLE package for communication and discovering devices and connecting
  app_settings: ^4.2.0    # to open settings from app
  get: ^4.6.5    # state management getx
  animated_toggle_switch: ^0.6.2   # toggle switch for on/off purposes [animated]
  toggle_switch: ^2.1.0    # toggle switch for on/off purposes
  connectivity_plus: ^3.0.6    # To get the information about the device connections
  device_info_plus: ^9.0.1    # to get the ip address and other info about phone
  audioplayers: ^4.0.1  # used to play audio
  just_audio: ^0.9.32    # # used to play audio
  crypto: ^3.0.2    # To implement cryptographic functions like creating SHA
  ffmpeg_kit_flutter: ^5.1.0   # used for streaming and saving audio through ffmpeg

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0   # To change the package name of the app


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
